
site_name: Xeno Docs
site_description: Xenoblade Chronicles Docs
site_url: https://nenkai.github.io/xb-docs/
repo_url: https://github.com/Nenkai/xb-docs
repo_name: nenkai/xb-docs

copyright: Copyright &copy; 2023 Nenkai

theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.png

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - content.action.edit
    - content.code.annotate
    - header.autohide
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: blue
      accent: blue 
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode    
      primary: blue
      accent: blue

nav:
  - Main Page: index.md
    
  - XC1DE:
    - Index: xc1de/index.md
    - Script API:
      - OCs:
        - Builtin: xc1de/script/oc/Builtin.md
        - Bdat: xc1de/script/oc/Bdat.md
        - Thread: xc1de/script/oc/Thread.md
        # todo: msg, unit, cfp

      - Plugins: 
        - Battle: xc1de/script/plugins/Btl.md
        - Camera: xc1de/script/plugins/Cam.md
        - Cfs: xc1de/script/plugins/Cfs.md # todo
        - Debug: xc1de/script/plugins/Deb.md
        - Event: xc1de/script/plugins/Eve.md
        - Game: xc1de/script/plugins/Game.md
        - Help: xc1de/script/plugins/Help.md
        - Math: xc1de/script/plugins/Math.md
        - Pad: xc1de/script/plugins/Pad.md
        - Sound: xc1de/script/plugins/Sound.md
        - Time: xc1de/script/plugins/Time.md
        - UI: xc1de/script/plugins/Ui.md
        - Unit: xc1de/script/plugins/Unit.md
        - Voice: xc1de/script/plugins/Voice.md
        - Wait: xc1de/script/plugins/Wait.md

    - Bdat:
      - bdat_common: xc1de/tables/bdat_common.md

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.critic
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search:
      lang: en
  - glightbox
      
extra_css:
  - stylesheets/extra.css